### ISSUE TITLE
SigSegv upon calling encode()

### ISSUE THREAD

**Issue by baltedewit** [Streampunk/beamcoder#3] opened 2019-03-07 10:27 UTC
Hi, I'm experimenting with this library trying to understand it better and decided to try and process Macadam frames:

```javascript
const macadam = require('macadam')
const beamcoder = require('beamcoder')

console.log('Starting sdi-http')
console.log('Decklink API version:', macadam.deckLinkVersion())

macadam.capture({
    deviceInfo: 0, // Index relative to the 'macadam.getDeviceInfo()' array
    displayMode: macadam.bmdModeHD720p50,
    pixelFormat: macadam.bmdFormat8BitYUV
}).then(async capture => {
    console.log(capture)
    const f = await capture.frame()
    capture.stop()
    console.log(f)

    let enc = await beamcoder.encoder({ // Create an encoder for JPEG data
        name : 'mjpeg', // FFmpeg does not have an encoder called 'jpeg'
        width : f.video.width,
        height: f.video.height,
        pix_fmt: 'yuvj422p',
        time_base: [1, 1] })

    let frame = await beamcoder.frame({ // Create a frame for the encoder
        width : f.video.width,
        height: f.video.height,
        format: 'uyvy422', // format received from macadam
        pts: 0
    }).alloc()

    f.video.data.copy(frame.data[0]) // copy data from macadam
    let jpg = await enc.encode(frame)
    await enc.flush()

    console.log(jpg) // eventually do something useful here
})
```

However, when I call the `enc.encode` I get the following SIGSEGV error:

```
PID 26452 received SIGSEGV for address: 0x2da744da
SymInit: Symbol-SearchPath: '.;C:\Users\balte\Documents\devProjects\sdi-http;C:\Program Files\nodejs;C:\WINDOWS;C:\WINDOWS\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'balte'
OS-Version: 10.0.17134 () 0x100-0x1
c:\users\balte\documents\devprojects\sdi-http\node_modules\segfault-handler\src\stackwalker.cpp (941): StackWalker::ShowCallstack
c:\users\balte\documents\devprojects\sdi-http\node_modules\segfault-handler\src\segfault-handler.cpp (235): segfault_handler
00007FFF2E6978D8 (ntdll): (filename not available): RtlInitializeCriticalSection
00007FFF2E63D4FA (ntdll): (filename not available): RtlWalkFrameChain
00007FFF2E6CE70E (ntdll): (filename not available): KiUserExceptionDispatcher
00007FFF2DA744DA (msvcrt): (filename not available): memmove
00007FFECC9F0426 (avcodec-58): (filename not available): avpriv_mpegaudio_decode_header
00007FFECC70C189 (avcodec-58): (filename not available): avcodec_encode_video2
00007FFECC70C506 (avcodec-58): (filename not available): avcodec_encode_video2
00007FFECC70C643 (avcodec-58): (filename not available): avcodec_send_frame
c:\users\balte\documents\devprojects\sdi-http\node_modules\beamcoder\src\encode.cc (162): encodeExecute
00007FF717FF54DF (node): (filename not available): uv_timer_set_repeat
00007FF717FE4058 (node): (filename not available): uv_once
00007FF718A03900 (node): (filename not available): v8::internal::compiler::OperationTyper::ToBoolean
00007FFF2BC83DC4 (KERNEL32): (filename not available): BaseThreadInitThunk
00007FFF2E6A3691 (ntdll): (filename not available): RtlUserThreadStart
```

It's a bit above my head to debug this, so hopefully someone is able to give me some pointers on how to make this work.

**Comment by sparkpunkd** [comment] 2019-03-08 10:27
I think the issue is that the `mjpeg` encoder only accepts the following planar pixel formats:

    [ 'yuvj420p', 'yuvj422p', 'yuvj444p' ]

You can see this with the following:

    beamcoder.encoders()['mjpeg'].pix_fmts

You would need to convert the interleaved data from macadam into the planar form (data[0] for Y, data[1] for U and data[2] for V) before encoding.

However, I wish you had not got a segfault ... I'll see if I can turn this into a more friendly error before closing this issue.

**Comment by scriptorian** [comment] 2019-03-12 15:15
I have added an example app that has a filtering implementation that with small modifications should help you avoid this problem. Take a look at examples/jpeg_filter_app.js.

**Comment by scriptorian** [comment] 2019-03-12 16:43
Something like the following just before calling encode:
```javascript
  let filt = await beamcoder.filterer({
    filterType: 'video',
    inputParams: [{
      width: f.video.width,
      height: f.video.height,
      pixelFormat: 'uyvy422',
      timeBase: [ 1, 25 ],
      pixelAspect: [ 1, 1 ] }],
    outputParams: [{ pixelFormat: 'yuv422p' }],
    filterSpec: 'scale=640:360, colorspace=range=jpeg:all=bt709' })

  let filtResult = await filt.filter([{ frames: [ f ] }]);
  let filtFrame = filtResult[0].frames[0]
    
  let jpg = await enc.encode(filtFrame)
  ...
```
I haven't tested this as I don't have any BMD hardware at the moment - but I hope it helps!

**Comment by baltedewit** [comment] 2019-03-12 17:29
Yup, that's pretty much what I did:

```javascript
filterer = await beamcoder.filterer({
    filterType: 'video',
    inputParams: [
        {
            width: 1280,
            height: 720,
            pixelFormat: 'uyvy422',
            pixelAspect: [1, 1],
            timeBase: [1, 1]
        }
    ],
    outputParams: [
        {
            pixelFormat: 'yuvj422p'
        }
    ],
    filterSpec: 'format=pix_fmts=yuvj422p'
})

let filtFrames = await filterer.filter([{ frames: { frames: [ frame ] } }])
let jpg = await enc.encode(filtFrames[0].frames[0])
```

**Comment by scriptorian** [comment] 2019-03-12 17:36
Great. 
FFmpeg has deprecated yuvj422p format apparently - you will probably be seeing a warning about this. In my example I have used the yuv422p format and used a colorspace filter to set the jpeg output range.

**Comment by sparkpunkd** [comment] 2019-03-12 17:43
SigSev issue is too deep inside FFmpeg to defend against. Ideally the MJPEG encoder could be at little nicer.

Closing as main issue is resolved.

**Closed by sparkpunkd** 2019-03-12 17:43 UTC
